import React from "react";
import { Download, Share2, CheckCircle2, ShieldCheck, ArrowRight, LifeBuoy, Check } from "lucide-react";
import { MarkdownRenderer } from "./Shared";

const ReportView = ({ content }: { content: string }) => {
  return (
    <div className="min-h-screen bg-obsidian text-slate-50 relative">
      <style>{`
        @media print {
            @page { margin: 10mm; }
            body { 
                background-color: white !important; 
                color: black !important; 
                -webkit-print-color-adjust: exact; 
                print-color-adjust: exact;
            }
            .no-print { display: none !important; }
            /* Hide all fixed elements like headers */
            .fixed { display: none !important; }
            
            /* Main container reset */
            .min-h-screen { 
                min-height: auto !important; 
                background: white !important;
                padding: 0 !important;
            }
            
            /* Report Card overrides */
            #report-container {
                border: 2px solid black !important;
                box-shadow: none !important;
                margin: 0 !important;
                padding: 20px !important;
                width: 100% !important;
                page-break-inside: avoid;
            }

            /* System Status Card overrides */
            .system-status-card {
                background: white !important;
                border: 2px solid black !important;
                color: black !important;
                box-shadow: none !important;
                margin-bottom: 20px !important;
            }
            .system-status-card * {
                color: black !important;
                border-color: black !important;
            }
            
            /* Text colors */
            .text-slate-50, .text-slate-400, .text-white, .text-neo-mint {
                color: black !important;
            }
            
            /* Prose overrides */
            .prose { 
                max-width: 100% !important; 
            }
        }
      `}</style>
      
      {/* 
        Sticky Header 
      */}
      <div className="fixed top-0 left-0 right-0 z-50 bg-neo-black border-b-4 border-white shadow-[0_4px_20px_rgba(0,0,0,0.5)] h-20 flex items-center no-print">
         <div className="w-full max-w-7xl mx-auto px-6 flex justify-between items-center">
             <div className="flex items-center gap-3">
                <div className="w-3 h-3 bg-neo-mint rounded-full animate-pulse shadow-[0_0_10px_#00E699]"></div>
                <div className="flex flex-col">
                    <span className="font-heading font-black uppercase tracking-widest text-sm text-white leading-none">Minus Protocol</span>
                    <span className="font-mono font-bold text-[10px] text-neo-mint leading-none">Live Analysis</span>
                </div>
             </div>
             {/* Top Button Removed as requested */}
         </div>
      </div>

      {/* 
        Main Content Container
      */}
      <div className="max-w-4xl mx-auto space-y-8 p-6 md:p-12 pb-32 pt-28">
         
         {/* System Status Card */}
         <div className="system-status-card bg-neutral-900 border-2 border-white p-6 md:p-8 shadow-neo animate-in fade-in slide-in-from-bottom-4 duration-700">
            <div className="flex justify-between items-start mb-6">
                <div className="bg-neo-blue text-white px-3 py-1 font-mono text-xs font-bold border border-white">
                    SESSION ID: {Math.random().toString(36).substring(7).toUpperCase()}
                </div>
                <ShieldCheck className="w-8 h-8 text-neo-mint" />
            </div>
            <h1 className="text-3xl md:text-5xl font-heading font-black uppercase leading-none mb-4 tracking-tight">
               Your Economic <br/><span className="text-neo-mint">Hygiene Report</span>
            </h1>
            <p className="text-slate-400 font-mono text-sm border-t border-dashed border-white/20 pt-4">
               Generated by Minus Protocol • Gemini Engine
            </p>
         </div>

         {/* Main Content Render */}
         <div id="report-container" className="bg-paper text-black border-4 border-black p-6 md:p-12 shadow-[12px_12px_0px_0px_#00E699] relative overflow-hidden animate-in fade-in slide-in-from-bottom-8 duration-1000 delay-200">
            
            {/* Watermark */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-[0.03] pointer-events-none">
               <span className="text-[10rem] font-black uppercase rotate-[-30deg] block">MINUS</span>
            </div>

            {/* AI Generated Content */}
            <div className="relative z-10 prose prose-lg max-w-none prose-headings:font-heading prose-headings:uppercase prose-headings:font-black prose-p:font-medium prose-li:font-bold prose-strong:text-black prose-strong:font-black">
               <MarkdownRenderer content={content} />
            </div>

            {/* Footer Seal */}
            <div className="mt-16 pt-8 border-t-4 border-black border-dashed flex items-center justify-between">
               <div className="flex items-center gap-3">
                  <CheckCircle2 className="w-8 h-8 text-neo-mint bg-black rounded-full p-1" />
                  <div>
                      <span className="block font-heading font-black uppercase text-lg leading-none">Mathematically</span>
                      <span className="block font-heading font-black uppercase text-lg leading-none text-slate-500">Verified</span>
                  </div>
               </div>
               <div className="text-right">
                  <p className="font-mono text-[10px] font-bold uppercase text-slate-500">Minus Protocol Inc.</p>
               </div>
            </div>
         </div>

         {/* Section 9: Buttons (CTA) - Hidden in Print */}
         <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-4 animate-in fade-in slide-in-from-bottom-8 duration-700 delay-500 no-print">
            {/* Download */}
            <button 
                onClick={() => window.print()}
                className="group bg-white border-4 border-black p-6 flex flex-col justify-between h-32 hover:-translate-y-1 hover:shadow-[6px_6px_0px_0px_white] transition-all"
            >
                <Download className="w-8 h-8 text-black group-hover:scale-110 transition-transform" />
                <span className="font-heading font-black text-lg uppercase text-black text-left leading-none">Download Plan (PDF)</span>
            </button>

            {/* Understand */}
            <button className="group bg-neo-mint border-4 border-black p-6 flex flex-col justify-between h-32 hover:-translate-y-1 hover:shadow-[6px_6px_0px_0px_white] transition-all shadow-[4px_4px_0px_0px_white]">
                <Check className="w-8 h-8 text-black group-hover:scale-110 transition-transform" />
                <span className="font-heading font-black text-lg uppercase text-black text-left leading-none">I Understand & Will Follow</span>
            </button>

            {/* Help */}
            <button className="group bg-neo-black border-4 border-white p-6 flex flex-col justify-between h-32 hover:-translate-y-1 hover:shadow-[6px_6px_0px_0px_#F2C94C] transition-all">
                <LifeBuoy className="w-8 h-8 text-white group-hover:text-neo-yellow group-hover:scale-110 transition-transform" />
                <div className="text-left">
                    <span className="block font-heading font-black text-lg uppercase text-white leading-none">Need Human Help</span>
                    <span className="block font-mono text-xs font-bold text-slate-500 mt-1 uppercase">(Optional)</span>
                </div>
            </button>
         </div>

      </div>
    </div>
  );
};

export default ReportView;