import React from "react";
import { Download, Share2, CheckCircle2, ShieldCheck } from "lucide-react";
import { MarkdownRenderer } from "./Shared";

const ReportView = ({ content }: { content: string }) => {
  return (
    <div className="min-h-screen bg-obsidian text-slate-50 relative">
      
      {/* 
        Sticky Header 
        Fixed height (h-16 = 64px) to allow content padding calculation.
      */}
      <div className="fixed top-0 left-0 right-0 z-50 bg-neo-black border-b-4 border-white shadow-[0_4px_20px_rgba(0,0,0,0.5)] h-20 flex items-center">
         <div className="w-full max-w-7xl mx-auto px-6 flex justify-between items-center">
             <div className="flex items-center gap-3">
                <div className="w-3 h-3 bg-neo-mint rounded-full animate-pulse shadow-[0_0_10px_#00E699]"></div>
                <div className="flex flex-col">
                    <span className="font-heading font-black uppercase tracking-widest text-sm text-white leading-none">Minus Protocol</span>
                    <span className="font-mono font-bold text-[10px] text-neo-mint leading-none">Live Analysis</span>
                </div>
             </div>
             <div className="flex gap-2">
                <button className="bg-white text-black px-4 py-2 font-bold font-mono text-xs uppercase border-2 border-black shadow-[4px_4px_0px_0px_rgba(255,255,255,1)] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-[2px_2px_0px_0px_rgba(255,255,255,1)] transition-all flex items-center gap-2">
                   <Download className="w-4 h-4" /> <span className="hidden md:inline">Save PDF</span>
                </button>
             </div>
         </div>
      </div>

      {/* 
        Main Content Container
        Added 'pt-28' (112px) to clear the fixed header (80px) + spacing.
      */}
      <div className="max-w-4xl mx-auto space-y-8 p-6 md:p-12 pb-32 pt-28">
         
         {/* System Status Card */}
         <div className="bg-neutral-900 border-2 border-white p-6 md:p-8 shadow-neo animate-in fade-in slide-in-from-bottom-4 duration-700">
            <div className="flex justify-between items-start mb-6">
                <div className="bg-neo-blue text-white px-3 py-1 font-mono text-xs font-bold border border-white">
                    SESSION ID: {Math.random().toString(36).substring(7).toUpperCase()}
                </div>
                <ShieldCheck className="w-8 h-8 text-neo-mint" />
            </div>
            <h1 className="text-3xl md:text-5xl font-heading font-black uppercase leading-none mb-4 tracking-tight">
               Your Economic <br/><span className="text-neo-mint">Hygiene Report</span>
            </h1>
            <p className="text-slate-400 font-mono text-sm border-t border-dashed border-white/20 pt-4">
               Generated by Minus Protocol v14.0 • Gemini 2.5 Flash Engine
            </p>
         </div>

         {/* Main Content Render */}
         <div className="bg-paper text-black border-4 border-black p-6 md:p-12 shadow-[12px_12px_0px_0px_#00E699] relative overflow-hidden animate-in fade-in slide-in-from-bottom-8 duration-1000 delay-200">
            
            {/* Watermark */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-[0.03] pointer-events-none">
               <span className="text-[10rem] font-black uppercase rotate-[-30deg] block">MINUS</span>
            </div>

            <div className="relative z-10 prose prose-lg max-w-none prose-headings:font-heading prose-headings:uppercase prose-headings:font-black prose-p:font-medium prose-li:font-bold">
               <MarkdownRenderer content={content} />
            </div>

            {/* Footer Seal */}
            <div className="mt-16 pt-8 border-t-4 border-black border-dashed flex items-center justify-between">
               <div className="flex items-center gap-3">
                  <CheckCircle2 className="w-8 h-8 text-neo-mint bg-black rounded-full p-1" />
                  <div>
                      <span className="block font-heading font-black uppercase text-lg leading-none">Mathematically</span>
                      <span className="block font-heading font-black uppercase text-lg leading-none text-slate-500">Verified</span>
                  </div>
               </div>
               <div className="text-right">
                  <p className="font-mono text-[10px] font-bold uppercase text-slate-500">Minus Protocol Inc.</p>
               </div>
            </div>
         </div>
      </div>
    </div>
  );
};

export default ReportView;